// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzY5q8Vq2zU2mb66cdbqDB7g9rCfI8DlM',
    appId: '1:154278314040:web:62a3a1196ea1b9c02aa6cd',
    messagingSenderId: '154278314040',
    projectId: 'nxtstep-app',
    authDomain: 'nxtstep-app.firebaseapp.com',
    storageBucket: 'nxtstep-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB55ukl4-XIgJXbRLy2x1k2UIlMTsLCxIo',
    appId: '1:154278314040:android:04ffab8a1584178e2aa6cd',
    messagingSenderId: '154278314040',
    projectId: 'nxtstep-app',
    storageBucket: 'nxtstep-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqqFRBhuaRZogB19tBHHeMiuVRId98Trw',
    appId: '1:154278314040:ios:55c54e611da656752aa6cd',
    messagingSenderId: '154278314040',
    projectId: 'nxtstep-app',
    storageBucket: 'nxtstep-app.firebasestorage.app',
    iosBundleId: 'com.example.nxtstep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqqFRBhuaRZogB19tBHHeMiuVRId98Trw',
    appId: '1:154278314040:ios:55c54e611da656752aa6cd',
    messagingSenderId: '154278314040',
    projectId: 'nxtstep-app',
    storageBucket: 'nxtstep-app.firebasestorage.app',
    iosBundleId: 'com.example.nxtstep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzY5q8Vq2zU2mb66cdbqDB7g9rCfI8DlM',
    appId: '1:154278314040:web:b64636983f3b18b42aa6cd',
    messagingSenderId: '154278314040',
    projectId: 'nxtstep-app',
    authDomain: 'nxtstep-app.firebaseapp.com',
    storageBucket: 'nxtstep-app.firebasestorage.app',
  );
}
